---

- name: install perl-Nagios-Plugin
  remote_user: "{{ remote_user }}"
  sudo: True
  yum: name={{ item }} state=present
  with_items:
    - perl-Nagios-Plugin
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")

- name: deploy squid.conf file (Centos)
  sudo: True
  remote_user: "{{ remote_user }}"
  copy: >
    src=squid.conf dest={{ icinga2_conf_path }}/squid.conf owner={{ icinga2_centos_user }} group={{ icinga2_client_group }} mode=0640
  sudo: True
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")

- name: deploy check_squid file (Centos)
  sudo: True
  remote_user: "{{ remote_user }}"
  copy: >
    src=check_squid dest={{ icinga2_plugin_path }}/check_squid owner=root group=root mode=0755
  sudo: True
  notify: restart icinga2
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")

