---

- name: install icinga2 check_mysql
  remote_user: "{{ remote_user }}"
  sudo: True
  yum: name={{ item }} state=present
  with_items:
    - nagios-plugins-mysql-2.0.3
  notify: restart icinga2
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")

- name: deploy mysql.conf file (Centos)
  sudo: True
  remote_user: "{{ remote_user }}"
  copy: >
    src=mysql.conf dest={{ icinga2_conf_path }}/mysql.conf owner={{ icinga2_centos_user }} group={{ icinga2_centos_group }} mode=0644
  sudo: True
  notify: restart icinga2
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")

