---

- name: add icinga2 yum repo
  copy: >
    src=ICINGA-release.repo dest={{ yum_repo_path }}/ICINGA-release.repo owner=root group=root mode=0644
  sudo: True

- name: add epel yum repo
  copy: >
    src=epel.repo dest={{ yum_repo_path }}/epel.repo owner=root group=root mode=0644
  sudo: True

- name: install icinga2 client
  remote_user: "{{ remote_user }}"
  sudo: True
  yum: name={{ item }} state=present
  with_items:
    - icinga2-2.4.4
    - icinga2-bin-2.4.4
    - icinga2-common-2.4.4
    - nagios-plugins-2.0.3
    - nagios-plugins-procs-2.0.3
    - nagios-plugins-ssh-2.0.3
    - nagios-plugins-disk-2.0.3
    - nagios-plugins-ping-2.0.3
    - nagios-plugins-users-2.0.3
    - nagios-plugins-load-2.0.3
    - nagios-plugins-http-2.0.3
    - nagios-plugins-dummy-2.0.3
    - nagios-common-3.5.1
    - nagios-plugins-swap-2.0.3
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
  notify: restart icinga2

- name: vault vars debug
  sudo: True
  debug: msg="my secure variable '{{ salt }}'"

- name: Transfer the script
  sudo: True
  template: src=icinga2_setup_client.j2 dest=/tmp/icinga2_setup_client.sh mode=0740

- name: check if file /tmp/icinga2_setup_client.sh exists
  stat: path=/tmp/icinga2_setup_client.sh
  register: file_stat

- name: setup node
  sudo: True
  command: /tmp/icinga2_setup_client.sh
  when: file_stat.stat.exists == True

- name: deploy check_yum command file
  copy: >
    src=check_yum dest={{ nagios_plugin_path }}/check_yum owner=root group=root mode=0755
  sudo: True
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
  notify: restart icinga2

- name: deploy yum.conf configuration file
  copy: >
    src=yum.conf dest={{ icinga2_conf_path }}/yum.conf owner=root group=root mode=0755
  sudo: True
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
  notify: restart icinga2

- name: delete file /tmp/icinga2_setup_client.sh
  become: yes
  file: path=/tmp/icinga2_setup_client.sh state=absent
  when: file_stat.stat.exists == True

