---
- name: create directory for ysar
  file: >
    path=/home/fih state=directory owner={{ remote_user }} group={{ remote_user }} mode=0755
    path=/home/fih/bin state=directory owner={{ remote_user }} group={{ remote_user }} mode=0755
    path=/home/fih/sbin state=directory owner={{ remote_user }} group={{ remote_user }} mode=0755
    path=/home/fih/logs/ysar state=directory owner={{ remote_user }} group={{ remote_user }} mode=0755 recurse=yes

- name: deploy ysar
  copy: >
    src=ysar dest={{ fih_home }}/bin/ysar owner={{ remote_user }} group={{ remote_user }} mode=0755
    src=ysar_gather dest={{ fih_home }}/sbin/ysar_gather owner={{ remote_user }} group={{ remote_user }} mode=0744
  sudo: True

- name: setup cron for ysar
  cron: >
    name="ysar" minute="*" hour="*" job="/home/fih/sbin/ysar_gather"
  sudo: True

