---

- name: install icinga2 check_procs
  remote_user: "{{ remote_user }}"
  become: yes
  yum: name={{ item }} state=present
  with_items:
    - nagios-plugins-procs-2.0.3
  notify: restart icinga2
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")

- name: deploy filebeat.conf file (Centos)
  become: yes
  remote_user: "{{ remote_user }}"
  copy: >
    src=filebeat.conf dest={{ icinga2_conf_path }}/filebeat.conf owner={{ icinga2_centos_user }} group={{ icinga2_centos_group }} mode=0644
  notify: restart icinga2
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")


