---

- name: add icinga2 yum repo
  copy: >
    src=ICINGA-release.repo dest={{ yum_repo_path }}/ICINGA-release.repo owner=root group=root mode=0644
  become: yes
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7")


- name: add epel6 yum repo
  copy: >
    src=epel.repo dest={{ yum_repo_path }}/epel.repo owner=root group=root mode=0644
  become: yes
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")

- name: add epel7 yum repo
  copy: >
    src=epel7.repo dest={{ yum_repo_path }}/epel.repo owner=root group=root mode=0644
  become: yes
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")


- name: install epel-release-6-8 key
#  remote_user: "{{ remote_user }}"
  become: yes
  yum: name={{ item }} state=present
  with_items:
    - epel-release
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
# sudo yum -y  install http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm

- name: install icinga2 client on centos6
#  remote_user: "{{ remote_user }}"
  become: yes
  yum: name={{ item }} state=present
  with_items:
    - icinga2
    - icinga2-bin-2.4.10
    - icinga2-common-2.4.10
    - nagios-plugins-2.0.3
    - nagios-plugins-procs-2.0.3
    - nagios-plugins-ssh-2.0.3
    - nagios-plugins-disk-2.0.3
    - nagios-plugins-ping-2.0.3
    - nagios-plugins-users-2.0.3
    - nagios-plugins-load-2.0.3
    - nagios-plugins-http-2.0.3
    - nagios-plugins-dummy-2.0.3
    - nagios-common-3.5.1
    - nagios-plugins-swap-2.0.3
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
  notify: restart icinga2

- name: install icinga2 client on centos7
  remote_user: "{{ remote_user }}"
  become: yes
  yum: name={{ item }} state=present
  with_items:
    - icinga2-2.4.10
    - icinga2-bin-2.4.10
    - icinga2-common-2.4.10
    - nagios-plugins-2.0.3
    - nagios-plugins-procs-2.0.3
    - nagios-plugins-ssh-2.0.3
    - nagios-plugins-disk-2.0.3
    - nagios-plugins-ping-2.0.3
    - nagios-plugins-users-2.0.3
    - nagios-plugins-load-2.0.3
    - nagios-plugins-http-2.0.3
    - nagios-plugins-dummy-2.0.3
    - nagios-common-4.0.8
    - nagios-plugins-swap-2.0.3
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
  notify: restart icinga2
  register: pkgs_stat

- name: change /etc/icinga2/pki owner to icinga
  become: yes
  file: path=/etc/icinga2/pki state=directory
        owner=icinga group=icinga 
        mode=0755

- name: Transfer the script
  become: yes
  template: src=icinga2_setup_client.j2 dest=/tmp/icinga2_setup_client.sh mode=0740

- name: check if file /tmp/icinga2_setup_client.sh exists
  stat: path=/tmp/icinga2_setup_client.sh
  register: file_stat

- name: setup node
  become: yes
  command: /tmp/icinga2_setup_client.sh
  when: file_stat.stat.exists == True

- name: install yum-plugin-security
#  remote_user: "{{ remote_user }}"
  become: yes
  yum: name={{ item }} state=present
  with_items:
    - yum-plugin-security-1.1.30
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")

- name: deploy check_yum command file
  copy: >
    src=check_yum dest={{ nagios_plugin_path }}/check_yum owner=root group=root mode=0755
  become: yes
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7")
  notify: restart icinga2

- name: deploy yum.conf configuration file
  copy: >
    src=yum.conf dest={{ icinga2_conf_path }}/yum.conf owner=root group=root mode=0755
  become: yes
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7")
  notify: restart icinga2

- name: delete file /tmp/icinga2_setup_client.sh
  become: yes
  file: path=/tmp/icinga2_setup_client.sh state=absent
  when: file_stat.stat.exists == True

