---

#  rpm --import http://packages.icinga.org/icinga.key

- name: install icinga2 server
  remote_user: "{{ remote_user }}"
  become: yes
  yum: name={{ item }} state=present
  with_items:
    - icinga2-2.4.10
    - icinga2-bin-2.4.10
    - icinga2-common
    - icinga2-doc
    - icinga2-ido-mysql
    - icingaweb2
    - icingacli
    - nagios-plugins-2.0.3
    - nagios-common-3.5.1
    - nagios-plugins-procs-2.0.3
    - nagios-plugins-ssh-2.0.3
    - nagios-plugins-disk-2.0.3
    - nagios-plugins-ping-2.0.3
    - nagios-plugins-users-2.0.3
    - nagios-plugins-load-2.0.3
    - nagios-plugins-http-2.0.3
    - nagios-plugins-dummy-2.0.3
    - nagios-plugins-swap-2.0.3
    - nagios-plugins-perl-2.0.3
    - perl-libwww-perl-5.833
    - mysql-server-5.1.73
    - httpd-2.2.15
    - php-ldap-5.3.3
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")

- name: deploy check command file
  copy: >
    src=check_squid dest={{ nagios_plugin_path }}/check_squid owner=root group=root mode=0755
  become: yes
  notify: restart icinga2

- name: deploy configuration file
  copy: src={{ item }} dest={{ icinga2_conf_path }}/{{ item }} owner={{ icinga2_user }} group={{ icinga2_group }} mode=0644
  with_items:
    - hosts.conf
    - services.conf
    - web-proxy.conf
    - yum.conf
    - notifications.conf
    - templates.conf
  become: yes
  notify: restart icinga2

- name: deploy scripts file
  copy: src={{ item }} dest={{ icinga2_scripts_path }}/{{ item }} owner=root group=root mode=0755
  with_items:
    - mail-service-notification.sh
  become: yes
  notify: restart icinga2

